version: '3'
services:
  db:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: dangerous
      MYSQL_DATABASE: realworld
    ports:
      - 3307:3306
    volumes:
      - "./data:/var/lib/mysql"