version: '3'
services:
  db:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: dangerous
      MYSQL_DATABASE: realworld
    ports:
      - 3307:3306
    volumes:
      - "./mysql/data:/var/lib/mysql"
  consul:
    image: consul
    ports:
      - 8501:8500
      - 8601:8600